esphome:
  name: esp-rfbridge
  platform: ESP8266
  board: nodemcu
  includes:
    - 433Sensor/RcSwitchSensor.h
  libraries:
    - "rc-switch"

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "##############"

ota:
  - platform: esphome
    password: "##############"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Rf-Bridge Fallback Hotspot"
    password: "##############"

captive_portal:

# Example configuration entry
sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new RcSwitchSensor();
    App.register_component(my_sensor);
    return {my_sensor};

  sensors:
    name: "433Sensor"